### ISSUE TITLE
Cura profile cannot be imported

### ISSUE THREAD

**Issue by Sebazzz** [bigtreetech/BIQU-B1#2]
The .curaprofile is a "legacy" profile and does no longer import in Cura 4.7. An error is show "could not find a quality type normal".

**Comment by thisiskeithb** [comment]
The B1 will be supported in Cura without needing to import profiles as soon as this PR is merged: https://github.com/Ultimaker/Cura/pull/8276

**Comment by Sebazzz** [comment]
Awesome!
