### ISSUE TITLE
illegal flash app

### ISSUE THREAD

**Issue by ejay-ibm** [bigtreetech/BIQU-B1#3]
I flash my TFT 35 with the latest firmware given on this git and now running this error message at boot time. 
The printer is not usable anymore please help quick . 
thank you

**Comment by Sebazzz** [comment]
@ejay-ibm Did you resolve your issue? 

If not, please check this and follow up: https://www.reddit.com/r/BIGTREETECH/comments/ioe06e/tft35_illegal_flash_app/ 👍

**Comment by ejay-ibm** [comment]
Yes resolved.  Firmware files should be deleted from cardboncevthe board is flashed. If you leave file on SD card and reboot the machine this issue can appear
