### ISSUE TITLE
Upgrading B1 with TMC2226 question

### ISSUE THREAD

**Issue by koiker** [bigtreetech/BIQU-B1#45]
Hi,

I've purchased the TMC2226 drivers to upgrade my BIQU B1 and would like to know if I just need to replace the original stepper drivers or do I need to change the firmware to work with the new drivers?
My idea is to enable the features from TMC2226 that doesn't exist in the TMC2225

**Comment by milekitic2017** [comment]
Hi i think that TMC2226(uart ?) its a upgrade from TMC2209 so if you have mainboard with TMC2209 drivers will be ok.If not change your firmware to TMC2209.

**Comment by koiker** [comment]
Thanks, it worked!
