### ISSUE TITLE
Air shroud - which material and settings?

### ISSUE THREAD

**Issue by Sebazzz** [bigtreetech/BIQU-B1#7]
The BIQU B1 air shroud - which material is it printed in?

And also, given that it is a 3d printed part, what was earlier, the chicken or the egg?

**Comment by thisiskeithb** [comment]
It should be printed in PETG at the very least. ABS/ASA or PC* would be ideal.

* The B1 can’t print true PC, but maybe you have a printer that can or you can have one printed from via print service.

**Comment by Sebazzz** [comment]
Alright - thank you.
