### ISSUE TITLE
illegal flash app

### ISSUE THREAD

**Issue by pentabene** [bigtreetech/BIQU-B1#9]
after updating to the latest tft firmware I got "illegal flash app" twice after starting the printer (immediately, no bisque boot screen)
had to reflash the tft.

anybody else with this problem?

**Comment by Ejay-3D** [comment]
You have remaining files from previous flash on your sd Card . 
You need 1 to reflash the screen , then 2 remove any files from the firmware flash ( including hidden files ._* on Mac os ) from the SD card .

**Comment by pentabene** [comment]
I did that. But strangely it also happened without sd card insterted.

**Comment by Ejay-3D** [comment]
Yes as i Saïd you need to reflash first to get rid of thé message

**Comment by pentabene** [comment]
So just to close this for good here is what you have to do in case you have the same issue as me:

Format your SD-Card as FAT32 (even if it is already FAT32, reformat it)
Refresh the Screen Firmware, you might even have to use an older Version if it does not work.
After the Update finishes take the SD-Card out of the TFT Slot and put it in your Computer. It should show the Firmware file wit .CUR in the end instead of .bin

**Now the most important Step:**

Format your SD-Card again as FAT32 **BEFORE** you put it back into the printer. It seems erasing them sometimes doesn't suffice, so I'd suggest to format it.
